In [1]:
from test_matrices import *
import scipy.sparse.linalg as lng
from scipy.sparse import csr_matrix, csc_matrix
import time
import numpy as np
from solver import *

In [2]:
A,b =generate_banded_csr(10)
b

array([[0.40731347],
       [0.        ],
       [0.58053372],
       [0.        ],
       [0.5205822 ],
       [0.40457039],
       [0.        ],
       [0.18407439],
       [0.94703131],
       [0.9113127 ]])

In [3]:
x, err, t = solve_gcrotmk(A,b)

convergence achieved


In [29]:
generate_test_matrices(10)

(array([[ 2., -1.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  3.,  0.,  0.,  0.,  0.,  0.],
        [ 0., -1.,  2., -1.,  0.,  3.,  0.,  0.,  0.,  0.],
        [ 3.,  0., -1.,  2., -1.,  0.,  3.,  0.,  0.,  0.],
        [ 0.,  3.,  0., -1.,  2., -1.,  0.,  3.,  0.,  0.],
        [ 0.,  0.,  3.,  0., -1.,  2., -1.,  0.,  3.,  0.],
        [ 0.,  0.,  0.,  3.,  0., -1.,  2., -1.,  0.,  3.],
        [ 0.,  0.,  0.,  0.,  3.,  0., -1.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  3.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  3.,  0., -1.,  2.]]),
 array([[20, -5,  0,  0,  0],
        [-5, 15, -5,  0,  0],
        [ 0, -5, 15, -5,  0],
        [ 0,  0, -5, 15, -5],
        [ 0,  0,  0, -5, 10]]),
 array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.17636744, 0.        ,
         0.        , 0.25996139, 0.   