In [1]:
import scipy.sparse.linalg as lng
from scipy.sparse import csr_matrix, csc_matrix
import time
import numpy as np
from scipy.sparse import coo_matrix, vstack, dok_matrix
from scipy.sparse import csr_matrix

In [2]:
a_p = 10
a_w = 2
a_n = 1
a_s = 3
a_e = 4
nx = 3
ny = 3

In [3]:
A = dok_matrix((nx*ny,nx*ny))
b = dok_matrix((nx*ny,1))

In [4]:
%%time
#inner matrix
for i in np.arange(1,ny-1):
    for j in np.arange(1,nx-1):
        k = (i*nx+j)
        A[k,k] = a_p
        A[k,k+1] = -a_e
        A[k,k-1] = -a_w
        A[k,k+nx] = -a_s
        A[k,k-nx] = -a_n
        print(k)

4
CPU times: total: 0 ns
Wall time: 0 ns


In [5]:
A.toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0., -2., 10., -4.,  0., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
#left boundary
j = 0
for i in np.arange(1,ny-1):
    k = (i*nx+j)
    A[k,k] = a_p
    A[k,k+1] = -a_e
    A[k,k+nx] = -a_s
    A[k,k-nx] = -a_n
    b[k] = a_w
    print(k)

3


In [7]:
#right boundary
j=nx-1
for i in np.arange(1,ny-1):
    k = (i*nx+j)
    A[k,k] = a_p
    A[k,k-1] = -a_w
    A[k,k+nx] = -a_s
    A[k,k-nx] = -a_n
    b[k] = a_e


In [8]:
b.toarray()

array([[0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [4.],
       [0.],
       [0.],
       [0.]])

In [17]:
a = []
a.append(np.array([1,2,3]))
a.append(np.array([4,5,6]))

In [18]:
np.asarray(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b = np.array([1,2,3,4,5,6])
b[0:2]

array([1, 2])