In [1]:
import scipy.sparse.linalg as lng
from scipy.sparse import csr_matrix, csc_matrix
import time
import numpy as np
from scipy.sparse import coo_matrix, vstack, dok_matrix
from scipy.sparse import csr_matrix

In [2]:
a_p = 10
a_w = 2
a_n = 1
a_s = 3
a_e = 4
nx = 3
ny = 3

In [3]:
A = dok_matrix((nx*ny,nx*ny))
b = dok_matrix((nx*ny,1))

In [5]:
a = np.arange(10)
b = a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
%%time
#inner matrix
for i in np.arange(1,ny-1):
    for j in np.arange(1,nx-1):
        k = (i*nx+j)
        A[k,k] = a_p
        A[k,k+1] = -a_e
        A[k,k-1] = -a_w
        A[k,k+nx] = -a_s
        A[k,k-nx] = -a_n
        print(k)

4
CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
A.toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0., -2., 10., -4.,  0., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
#left boundary
j = 0
for i in np.arange(1,ny-1):
    k = (i*nx+j)
    A[k,k] = a_p
    A[k,k+1] = -a_e
    A[k,k+nx] = -a_s
    A[k,k-nx] = -a_n
    b[k] = a_w
    print(k)

3


In [8]:
#right boundary
j=nx-1
for i in np.arange(1,ny-1):
    k = (i*nx+j)
    A[k,k] = a_p
    A[k,k-1] = -a_w
    A[k,k+nx] = -a_s
    A[k,k-nx] = -a_n
    b[k] = a_e


In [9]:
b.toarray()

array([[0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [4.],
       [0.],
       [0.],
       [0.]])

In [10]:
a = []
a.append(np.array([1,2,3]))
a.append(np.array([4,5,6]))

In [11]:
np.asarray(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.array([1,2,3,4,5,6])
b[0:2]

array([1, 2])

In [13]:
L = 100
nx = 10
r = 1.5
x_0 = ((1-r)/(1-r**(nx/2)))*L/2
delta_x = [x_0]

In [14]:
while round(sum(delta_x), ndigits=5) < L/2:
    x = delta_x[-1]*r
    delta_x.append(x)
    print(sum(delta_x))
delta_x = delta_x + list(reversed(delta_x))
delta_x

9.47867298578199
18.009478672985782
30.80568720379147
50.0


[3.7914691943127963,
 5.687203791469194,
 8.530805687203792,
 12.796208530805687,
 19.194312796208532,
 19.194312796208532,
 12.796208530805687,
 8.530805687203792,
 5.687203791469194,
 3.7914691943127963]

In [15]:
np.array(delta_x)
d_x = [x_0]

for i in np.arange(0,len(delta_x)-1):
    d_x_temp = delta_x[i]/2 + delta_x[i+1]/2
    d_x.append(d_x_temp)

In [16]:
d_x

[3.7914691943127963,
 4.739336492890995,
 7.109004739336493,
 10.66350710900474,
 15.99526066350711,
 19.194312796208532,
 15.99526066350711,
 10.66350710900474,
 7.109004739336493,
 4.739336492890995]

In [17]:
a = 3

if a<5:
    print('hallo')

if a == 3:
    print('nein')

hallo
nein


In [18]:
sum(delta_x)

100.00000000000001

In [19]:
a = [1, 2, 3]
print(list(reversed(a)))

[3, 2, 1]


In [20]:
a = np.zeros(shape=(10,10))
a[0,:] = 1
a[0,:] = a[0,:]+1
a

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])